from config_control import ConfigFlags, save_config

# the default config
# you can specify a new config by running
# poetry run snakemake -c1 --configfile config/new_config.yaml
# keys/values missing from the new config will be pulled from the default config
default_config = "config/default_config.yaml"


configfile: default_config


# set the name for results directory
# except for processed data and trained models that may be shared between many
# runs, all of the results from the workflow will be saved in this directory
results_dir = f"results/{config['run_name']}"
# set the location of the model used in this run
model_loc = f"models/{config['lgsm']['model_name']}"


# set path to the full config to be checked against and then saved
full_config = f"{results_dir}/full_config.yaml"
# set up the config flags
config_flags = ConfigFlags(config, full_config)


# save the current config
onstart:
    save_config(config, full_config, default_config)


rule all:
    input:
        config_flags.all_flags(),
        "data/processed/simulated_photometry.pkl",
        model_loc,
        f"{results_dir}/model_losses.{config['plotting']['model_losses']['format']}",


rule simulate_photometry:
    input:
        config_flags.flag("sims"),
        "data/raw/simulated_seds.pkl",
    output:
        "data/processed/simulated_photometry.pkl",
    script:
        "scripts/simulate_photometry.py"


rule train_LGSModel:
    input:
        config_flags.flag("lgsm"),
        "data/processed/simulated_photometry.pkl",
    output:
        directory(model_loc),
    script:
        "scripts/train_lgsmodel.py"


rule plot_model_loss:
    input:
        config_flags.flag("plotting"),
        model_loc,
    output:
        f"{results_dir}/model_losses.{config['plotting']['model_losses']['format']}",
    script:
        "scripts/plot_model_losses.py"


# cleanup the config flags
onerror:
    config_flags.cleanup()
onsuccess:
    config_flags.cleanup()
