name: lgsm
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - flake8-bugbear
  - flake8-simplify
  - isort
  - jupyterlab
  - matplotlib
  - mypy
  - numpy
  - pip
  - pyarrow
  - pytorch
  - python=3.11
  - seaborn
  - pip:
      - normflows
      - photerr
