# ----------------------------------------------------------------
# ----------------------------------------------------------------
# Name for this run. Except for processed data, which is saved in
# data/processed, and trained models, which are saved in models
# all the results will be saved in results/run_name
run_name: default # str

# ----------------------------------------
# settings for the photometry simulations
# ----------------------------------------
sims:
  random_seed: 0 # int
  redshifts_per_sed: 100 # int
  min_redshift: 0.01 # float
  max_redshift: 2. # float
  min_mag: 18. # float
  max_mag: 22. # float
  bandpasses: # Sequence[str]
    - lsstu
    - lsstg
    - lsstr
    - lssti
    - lsstz
    - lssty

# ----------------------------
# settings for the LGSM model
# ----------------------------
lgsm:
  model_name: default_model # str

  vae:
    encoder_layers: [32] # Sequence[int]
    intrinsic_latent_size: 3 # int
    decoder_layers: [8, 16, 32] # Sequence[int]
    wave_bins: 64 # int
    wave_min: 1.e+3 # float
    wave_max: 11.e+3 # float
    normalize_at: 4.e+3 # float
    sed_unit: mag # str, mag or flambda
    batch_norm: True # bool

  physics_layer:
    bandpasses: # Sequence[str]
      - lsstu
      - lsstg
      - lsstr
      - lssti
      - lsstz
      - lssty
    band_oversampling: 201 # int

  training:
    losses:
      MSE: {} # empty dict, because no parameters
      SlopeLoss:
        eta: 1.e-2 # float

    optimizer:
      adam:
        learning_rate: 1.e-3 # float

    batch_size: 128 # int
    epochs: 300 # int
    validation_split: 0.2 # float in [0, 1)

# ----------------------
# settings for plotting
# ----------------------
plotting:
  model_losses:
    format: png # str, e.g. png, pdf, svg, etc.
    subplots_settings: # dictionary passed to plt.subplots()
      nrows: 3 # int
      ncols: 1 # int
      figsize: [4, 7] # list
      constrained_layout: True # bool
      dpi: 120 # int
    plot_settings: # dictionary passed to ax.set()
      yscale: log # str
