run_name: infoVAE_a1_lessReg

lgsm:
  model_name: infoVAE_a1_lessReg_model

  training:
    losses:
      KLDiv:
        use: False # bool
      MMD:
        use: True # bool
        params:
          alpha: 1. # float
          beta: 1.e+2 # float, lambda from the InfoVAE paper
          nsamples: 200 # int
      SpectralLoss:
        use: True # bool
        params:
          frac: 0.01 # float
          eta: 1.e+1 # float
