run_name: spectral_loss

lgsm:
  model_name: spectral_loss_model

  training:
    losses:
      PhotometryMSE:
        use: True # bool
      SpectralLoss:
        use: True # bool
        params:
          frac: 0.01 # float
          eta: 1.e+2 # float
